### ISSUE TITLE
Error message when adding gradient with single Labels object as components argument is not clear, doc is wrong

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/metatensor#104]
When doing
```python
mean_block.add_gradient(
    parameter,
    mean_values.reshape(1,1,-1),
    Labels(['sample'], np.array([[0]], dtype=np.int32)),
    Labels.single()
)
```
The error message is 
```python
.../equistore/block.py:221, in TensorBlock.add_gradient(self, parameter, data, samples, components)
    219 components_array = ctypes.ARRAY(eqs_labels_t, len(components))()
    220 for i, component in enumerate(components):
--> 221     components_array[i] = component._as_eqs_labels_t()
    223 data = ArrayWrapper(data)
    225 self._lib.eqs_block_add_gradient(
    226     self._ptr,
    227     parameter.encode("utf8"),
   (...)
    231     len(components_array),
    232 )

AttributeError: 'numpy.void' object has no attribute '_as_eqs_labels_t'
```

The solution is to put the components Labels into a list
```python
mean_block.add_gradient(
    parameter,
    mean_values.reshape(1,1,-1),
    Labels(['sample'], np.array([[0]], dtype=np.int32)),
    [Labels.single()]
)
```
The doc also seems wrong here: the text for components looks exactly like for samples
```
help(X.block().add_gradient)
...python
    :param samples: labels describing the gradient samples
    :param components: labels describing the gradient components
```

**Comment by Luthaf** [comment]
So this is already documented through type annotation: https://github.com/lab-cosmo/equistore/blob/e65cd07d2f0d5aefa41a7b2beade835b9b1dc03b/python/src/equistore/block.py#L196-L202

but these don't show up in the `help` function output, so we should change the parameter to say something like `:param components: list of labels describing the gradient components`.

On the error message side of things, we should add more type checking before creating the C array of components here:
https://github.com/lab-cosmo/equistore/blob/e65cd07d2f0d5aefa41a7b2beade835b9b1dc03b/python/src/equistore/block.py#L219
