### ISSUE TITLE
Rename `TensorBlock` and `TensorMap`

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/metatensor#143]
In the last dev meeting, we talked about renaming the two core classes `TensorBlock` and `TensorMap`.

Naming our classes `Tensor` might confuse users because they think that these classes are tensors and they can apply standard operations on them. Up to a certain point, this is true but due to gradients, there is an additional complexity layer that goes beyond standard tensor operations.

We concluded that `TensorBlock` should be renamed to `Block`

However, for the `TensorMap`, we haven't found a git name. Simply calling it `Map` is a bad idea because it clashes with the function `map`. In my view, the `TensorMap` is a classical map for `Blocks`. Therefore, we could also name it `BlockMap` or `BlockFrame` (in a pandas spirit). If somebody has other ideas we can also discuss them here.

**Comment by Luthaf** [comment]
unlikely to happen
