### ISSUE TITLE
Formalize different kinds of keys

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/metatensor#185]
We are using keys/blocks for three separate concepts:

- block-sparse tensor in the sample dimension (i.e. `species_center`, will be moved to samples to create a dense tensor)
- block-sparse tensor in the feature dimension (i.e. `species_neighbor`, will be moved to properties to create a dense tensor)
- separate but related objects (i.e. `spherical_harmonics_l`, these are mostly about symmetry), which should not be moved to samples/properties but always treated as separate blocks.

It might be nice to formalize and carry this information directly inside a TensorMap, knowing which key have which kind. This would allow code in `equistore.operations` and `equisolve` to automatically make the tensor dense where required, and even provide a `TensorMap.densify() -> np.array` functionality.

On the other hand, this would also include another layer of complexity one has to think about before being able to create a TensorMap.

**Comment by Luthaf** [comment]
After a short in-person discussion, I realized that not everything is as clear-cut as I hoped here. For example, there is a use case for moving `center_species` to properties in addition to samples: this effectively creates a separate model for each center species.

**Comment by agoscinski** [comment]
I am not sure about the purpose of this. Is it about making the moving of keys more efficient?

**Comment by Luthaf** [comment]
This was a brain dump, but it is very unclear to me if this is actually doable/beneficial.

The core idea was that if we ascribe more meaning to the keys, the job of equisolve/equistore-operations would be easier when dealing with data not produced by rascaline (with its own set of key names).

With this extra metadata, features-sparse keys should always be merged when computing a kernel; but symmetry keys would be kept separate. Samples-sparse keys are a bit harder to handle unfortunately.

**Comment by Luthaf** [comment]
This is unlikely to happen at this point, closing the issue
