### ISSUE TITLE
`equistore.contiguous` operation, making all the data contiguous

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/metatensor#265]
We should have an operation to transform all data inside equistore into contiguous arrays. This is required in particular if one wants to use `equistore.save`, which only support contiguous arrays.

**Comment by agoscinski** [comment]
Could you give a bit more explanation on the function signature and in which way it is contiguous? Does it return an array `contiguous(X : TensorMap) -> Union[np.ndarray, torch.Tensor]` ? In this case, is it like a concatenation of all TensorBlocks in a TensorMap?

**Comment by Luthaf** [comment]
My idea was more to apply `ascontiguousarray` on each block one by one, so `contiguous(tensor: TensorMap) -> TensorMap`

**Comment by jwa7** [comment]
Stumbled across this issue and thought I'd share a function I already use in my code - might be helpful as a starting point for anyone that wants to take on this #goodfirstissue !

```python
def make_contiguous_numpy(tensor: TensorMap) -> TensorMap:
    """
    Takes a TensorMap of numpy backend and makes the ndarray block and
    gradient values contiguous in memory.
    """
    new_blocks = []
    for key, block in tensor.items():
        new_block = TensorBlock(
            values=np.ascontiguousarray(block.values),
            samples=block.samples,
            components=block.components,
            properties=block.properties,
        )
        for parameter, gradient in block.gradients():
            new_gradient = TensorBlock(
                values=np.ascontiguousarray(gradient.values),
                samples=gradient.samples,
                components=gradient.components,
                properties=gradient.properties,
            )
            new_block.add_gradient(parameter, new_gradient)
        new_blocks.append(new_block)

    return TensorMap(
        keys=tensor.keys,
        blocks=new_blocks,
    )
```

Note: the above does not handle second derivatives (gradients of gradients).
