### ISSUE TITLE
Labels cannot be pickled

### ISSUE THREAD

**Issue by HannaTuerk** [lab-cosmo/metatensor#321]
Hello, just updated my code to the newest version of equistore (dev333) and found the issue that Labels cannot be pickled (and thus not be saved with pickle.dumps)

Here a small example to replicate the error:

```py
from equistore import Labels
import pickle

l = Labels.empty("_")
pickle.dumps(l)
```

Gives this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Can't pickle local object 'CDLL.__init__.<locals>._FuncPtr'
```

**Comment by Luthaf** [comment]
I'm working on this.
