### ISSUE TITLE
Labels.sort and argsort in core

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/metatensor#366]
Because TorchScript does not support the `sort()` function for `List[List[int]]` which is required for sorting the metadata. We have currently a very hacky solution for the torch part. Therefore it would be good if we implement a `Labels.sort` function. 

Option 1
```
Labels.sort(reverse=...) -> (Labels, indices)`
```
Option 2
```
Labels.sort(reverse=...) -> Labels
Labels.argsort(reverse=...) -> indices
```
Second option seems to be a bit more consistent with what exists in numpy, but I don't have strong opinions.

Reference
https://github.com/lab-cosmo/metatensor/pull/281#discussion_r1323119969_

**Comment by Luthaf** [comment]
We found a workaround for this in #647, defining multiple functions to sort list of tuples with various arity
