### ISSUE TITLE
Improve error message when metatensor-core without metatensor is installed

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/metatensor#369]
We had the issue with @bananenpampe when metatensor-core is installed (for example when installing rascaline) and one tries to import TensorMap, the error message is confusing with its `unknown location`. For me it pin points more to a broken installation than a missing package.
```python
Cell In[4], line 1
----> 1 from metatensor import TensorMap

ImportError: cannot import name 'TensorMap' from 'metatensor' (unknown location)
```
The `unknown location` could be fixed by just adding an `__init__.py` into the `python/metatensor-core/metatensor`. But I guess there is a reason why we do not have an `__init__.py` with a `from .core import *` in the metatensor-core package, but only in the metatensor package? Maybe you have ideas to improve the error message somehow nevertheless.

**Comment by Luthaf** [comment]
This is going to be relatively hard to do … `metatensor-core` is a [namespace package](https://peps.python.org/pep-0420/), meaning it only installs itself in `<site-packages>/metatensor/core/`, and does not add files in `<site-packages>/metatensor`. 

I agree that this error message is bad and we should improve it. Maybe we can have `metatensor-core` not be a namespace package and create a file at `metatensor/__init__.py` with the content currently in metatensor. And metatensor would be an empty package with dependency on metatensor-core and metatensor-operations?

**Comment by Luthaf** [comment]
Making `metatensor` into an empty meta-package (package only containing dependency declarations looks like it could work:

- https://stackoverflow.com/questions/74111085/create-a-meta-package-from-an-existing-virtual-environment-in-python
- https://github.com/timofurrer/ptipython-meta/
