### ISSUE TITLE
`TensorBlock.to` and `TensorMap.to`

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/metatensor#412]
In #411 @frostedoyster added internal `TensorMap::to` and `TensorBlock::to` to metatensor-torch. It could be nice to expose these to the end user directly. On one hand it could be interesting, and play part of the role of `metatensor.to` operation; on the other hand we need the same API in metatensor-core.

For metatensor-core, calling `TensorMap.to("cuda")` would do nothing (maybe a warning?) if the arrays are numpy; and should move the values to CUDA is the arrays are torch. But they currently can not move the samples values. We could accept this limitation and document it; or not expose these new functions to Python.

Another solution (that would be a separate PR) could also be to do the same thing in -core as we do in -torch, and duplicate the labels values with the same arrays backend as the values, which in the torch case would allow to move them to GPU.

_Originally posted by @Luthaf in https://github.com/lab-cosmo/metatensor/pull/411#pullrequestreview-1707991069_

**Comment by Luthaf** [comment]
> Another solution (that would be a separate PR) could also be to do the same thing in -core as we do in -torch, and duplicate the labels values with the same arrays backend as the values, which in the torch case would allow to move them to GPU.

I think this would be the most correct way, and allow us to move everything to GPU. But it is also more tricky since it would have to use the very low-level memory management of `Labels::user_data`.

**Comment by frostedoyster** [comment]
In the second case, would we send e.g. a `metatensor.TensorBlock` into a `metatensor.torch.TensorBlock`?

**Comment by Luthaf** [comment]
What second case? `TensorBlock.to` in metatensor-core Python? I would not use this to convert between the two backends, only move data from one device to another (maybe also change the dtype?).

For changing backend, I think the best solution would be to put the code in operations, maybe `metatensor.to`?. The alternative of adding a static `TensorMap::from_core` would need to take a pointer in C++, and could not be used directly with the Python version.

**Comment by Luthaf** [comment]
Fixed by #439
