### ISSUE TITLE
`metatensor.torch.Labels.to` doesn't show correctly in the docs

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#434]
Here is how it shows now:

![image](https://github.com/lab-cosmo/metatensor/assets/98903385/e5eff7d8-53e4-4865-84e3-7e5bd5bf1e3b)

**Comment by Luthaf** [comment]
The documentation is using `@overload`, but it could (and I think it should) use `Union` instead: https://github.com/lab-cosmo/metatensor/blob/master/python/metatensor-torch/metatensor/torch/documentation.py#L430-L436

With overload, this is how the function is supposed to be documented: https://github.com/Luthaf/rascaline/blob/0e3e5e9dadbc8595d3adce4f3ff01a98e456c56f/python/rascaline-torch/rascaline/torch/system.py#L57C1-L97

**Comment by Luthaf** [comment]
oh, and the syntax is completely wrong: should be `to(self, device: str)`/`to(self, device: torch.device)` anyway for the `@overload` version. Was this written with ChatGPT/copilot?
