### ISSUE TITLE
Misleading documentation for `TensorBlock.gradients()` in `metatensor.torch`

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#448]
I was trying to get `block.gradients()`, which the documentation advertises as a `Dict[str, TensorBlock]`, but I wasn't able to call `.keys()` on it

**Comment by Luthaf** [comment]
Sounds like we forgot to update the docs in https://github.com/lab-cosmo/metatensor/pull/309. I'll do this quickly.
