### ISSUE TITLE
Inconsistent behavior when adding a `List` and a `TensorMap`

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/metatensor#454]
When applying the `add`/`+` operator onto a Python list (i.e. `tensors_list `) and a TensorMap (i.e. `tensor`) there is an inconsistent behavior. When using the `+` operator directly an error is thrown stating that "_can only concatenate list (not "TensorMap") to list_". However, when using the `iadd`/`+=`  operator, the blocks of the TensorMap are added to a list.

I don't know what I would expect but at least we should be consistent.

# Code to reproduce
```python
from metatensor import Labels, TensorMap, TensorBlock
import numpy as np

block = TensorBlock(values = np.array([[1]]),
    samples=Labels.single(),
    components=[],
    properties=Labels.single(),
)

ts = TensorMap(keys=Labels.single(), blocks=[block])
```

```python
tensors_list = []
tensors_list + ts
tensors_list
```

returns `TypeError: can only concatenate list (not "TensorMap") to list`

```python
tensors_list = []
tensors_list += ts
tensors_list
```

returns 

```
[TensorBlock
     samples (1): ['_']
     components (): []
     properties (1): ['_']
     gradients: None]
```

**Comment by Luthaf** [comment]
Hmm, I guess `+=` for list implicitly iterate over the elements of the right hand side. This looks similar to 

```py
>>> a = "some string"
>>> l = []
>>> l + a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate list (not "str") to list
>>> l += a
>>> l
['s', 'o', 'm', 'e', ' ', 's', 't', 'r', 'i', 'n', 'g']
```

So not really related to metatensor, but more of a Python gotcha. I'm not sure there is anything we can do about this on our side.

**Comment by PicoCentauri** [comment]
Ahh might be. But maybe we can add an implementation for `iadd` checking the types?

**Comment by Luthaf** [comment]
I think (but we should check) that this is calling the list `iadd`, not the TensorMap one.

**Comment by PicoCentauri** [comment]
You are right, it will call the `iadd` of lists. Then I agree that there is at this point nothing we can do.
