### ISSUE TITLE
dtype of tensor map is 6

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/metatensor#464]
Pushed the branch [dtype6](https://github.com/lab-cosmo/metatensor/tree/dtype6) where this has happened. In the metatensor-learn test on the TorchScript API the test in file `linear.py`. The `single_block_tensor.dtype` is 6 there. Is this normal?

**Comment by Luthaf** [comment]
It's a known limitation of running TorchScript code inside Python: https://lab-cosmo.github.io/metatensor/latest/torch/reference/tensor.html#metatensor.torch.TensorMap.dtype

The fix is to do all of your dtype checking inside `@torch.jit.script` functions, as shown in the docs.
