### ISSUE TITLE
Different ordering in `join`, apart from the default lexicographical ordering, should be an option

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/metatensor#467]
Say we are collating 2 TensorMaps corresponding to different samples in order to form a minibatch, for instance using `metatensor.learn.data.group_and_join`, the default collate function of `metatensor.learn.data.DataLoader`. `join` will lexicographically sort the samples metadata, but in often it is useful to retain the original ordering. This is for instance important when joining TensorMap descriptors / targets but working with an ordered list of systems as input.

Perhaps `join` should come with user-controllable options for how to sort the (meta)data in the resulting TensorMap.

**MWE**

Joining two TensorMaps that are identical, except reverse ordered sample indices `1` and `0`, respectively:

```py
import numpy as np
import metatensor
from metatensor import Labels, TensorBlock, TensorMap

tensors = [
    TensorMap(  # sample "1"
        keys=Labels(names=["a"], values=np.array([[0]])),
        blocks=[
            TensorBlock(
                values=np.array([0]).reshape(-1, 1),
                samples=Labels(names=["s"], values=np.array([1]).reshape(-1, 1)),
                components=[],
                properties=Labels(names=["p"], values=np.array([0]).reshape(-1, 1)),
            )
        ]
    ),
    TensorMap(  # sample "0"
        keys=Labels(names=["a"], values=np.array([[0]])),
        blocks=[
            TensorBlock(
                values=np.array([0]).reshape(-1, 1),
                samples=Labels(names=["s"], values=np.array([0]).reshape(-1, 1)),
                components=[],
                properties=Labels(names=["p"], values=np.array([0]).reshape(-1, 1)),
            )
        ]
    ),
]

joined_tensor = metatensor.join(tensors, axis="samples", remove_tensor_name=True)
```

The order of the samples of the joined TensorMap are reversed:

```py
joined_tensor.block(0).samples
>>> Labels(
    s
    0
    1
)
```

This has implications for `metatensor-models` - tagging @frostedoyster, @agoscinski and @PicoCentauri involved in this.

**Comment by Luthaf** [comment]
This might be an easy fix: join uses `keys_to_samples`, which has a `sort_samples` argument, defaulting to `True`. We should mainly expose this as a kwargs on `join`, and make it default to `False`.

**Comment by PicoCentauri** [comment]
Ohh this might really something easy! I can give it a try!
