### ISSUE TITLE
Core Python Documentation returns a 404 error

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/metatensor#483]
When trying to visit the Python reference for the core class the documentation website returns a 404 error.

https://lab-cosmo.github.io/metatensor/latest/core/reference/python/index.html

This also causes problems for downstream packages and their intersphinx links i.e https://github.com/Luthaf/rascaline/pull/275

**Comment by Luthaf** [comment]
I have no idea what is going wrong. The files are not on gh-pages, but they where successfully generated in the latest build: https://github.com/lab-cosmo/metatensor/actions/runs/7759491847/job/21163626972

And then they are missing from the job taking gh-pages and creating the website (this is automatically done by github): https://github.com/lab-cosmo/metatensor/actions/runs/7759555481/job/21163844037

I'll try removing `latest` in gh-pages and re-triggering a build.

**Comment by Luthaf** [comment]
Oh, right. We have `python/` in the .gitignore. Should be an easy fix. 

Might be interesting to change the way we deploy docs to not have to push to a branch, with https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow.

**Comment by Luthaf** [comment]
Should be fixed now!

**Comment by PicoCentauri** [comment]
Wonderful. Thanks!
