### ISSUE TITLE
Consider splitting the rust crate into pure C bindings and Rust API on top

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/metatensor#510]
> Given that we need a new release of metatensor-rust for every release of metatensor-core, it might make sense to split the packages differently. A possibility would be to introduce a metatensor-sys package that only builds/find an existing metatensor C library, and keep metatensor as the one with a nice Rust API.

_Originally posted by @Luthaf in https://github.com/lab-cosmo/metatensor/issues/509#issuecomment-1938760062_

**Comment by PicoCentauri** [comment]
More metatensor packages!!!!

Sounds reasonable and I am not against if administrative release/changelog/docs overhead is not taking over.
