### ISSUE TITLE
`objects.inv` in `sphinx` docs appears to be corrupted

### ISSUE THREAD

**Issue by sirmarcel** [lab-cosmo/metatensor#515]
I'm trying to download offline docs for `metatensor` using the Dash app (but I doubt it's related to this app in particular). However, I'm getting the following error: `Error: Couldn't process objects.inv.` From a bit of googling it seems like [it's an issue with that file being corrupted](https://github.com/sphinx-doc/sphinx/issues/3488), but I'll have to look into it later in more detail. I'm assigning myself to this issue, so feel free to ignore it unless you have some direct insight into what's going on.

**Comment by Luthaf** [comment]
Did you had time to look into this?

**Comment by sirmarcel** [comment]
Not yet, I'll put it on the list for next week. Has this become urgent?

**Comment by Luthaf** [comment]
Not really, I'm just trying to clean up the set of open issues!

**Comment by sirmarcel** [comment]
Okay, I'll take a look if I can quickly fix this next week, otherwise we can just close it for now, as I think this doesn't have any impacts beyond not being able to download the docs.
