### ISSUE TITLE
Checking for a `TensorMap` in `metatensor-torch`, not a `torch.ScriptObject`

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/metatensor#524]
When trying to use `slice` from `metatensor-torch`, a `TypeError` is raised.

In file https://github.com/lab-cosmo/metatensor/blob/master/python/metatensor-operations/metatensor/operations/_backend.py, this torch scripting function always returns false:

```py
def torch_jit_is_scripting():
    return False
```

and thus in https://github.com/lab-cosmo/metatensor/blob/a9be3e759bf812f5aab058b46aaf8d56469374be/python/metatensor-operations/metatensor/operations/slice.py, the input tensor is checked for being a `TensorMap`, but fails because it's instead a `torch.ScriptObject`.

**MWE**
```py
import torch
import metatensor.torch as mts

block = mts.TensorBlock(
    values=torch.tensor([[1, 2], [3, 5]]),
    samples=mts.Labels(["s"], torch.tensor([[0], [2]])),
    components=[],
    properties=mts.Labels.range("p", 2),
)
mts.slice_block(block, "samples", mts.Labels(names=["s"], values=torch.tensor([[0]])))
```
raises: `TypeError: `tensor` must be a metatensor TensorMap, not <class 'torch.ScriptObject'>`.

Should the function `torch_jit_is_scripting` be modified, or is it a case of overriding type `TensorMap` with that of a `ScriptObject`? @Luthaf @PicoCentauri

**Comment by Luthaf** [comment]
The root issue is that you are passing a block to `slice` and not to `slice_block`. Does the error go away if you use the right function? 

If so, we should improve this error message for the torch script backend.

**Comment by jwa7** [comment]
@Luthaf Sorry yes, a typo in the MWE. But the issue still stands

**Comment by Luthaf** [comment]
The MWE still does not work. As written it produces 

```
Traceback (most recent call last):
  File "tmp.py", line 11, in <module>
    mts.slice_block(block, "samples", "s")
RuntimeError: slice_block() Expected a value of type '__torch__.torch.classes.metatensor.Labels (of Python compilation unit at: 0x0)' for argument 'labels' but instead found type 'str'.
Position: 2
Value: 's'
Declaration: slice_block(__torch__.torch.classes.metatensor.TensorBlock block, str axis, __torch__.torch.classes.metatensor.Labels labels) -> __torch__.torch.classes.metatensor.TensorBlock
Cast error details: Tried to cast object to type __torch__.torch.classes.metatensor.Labels (of Python compilation unit at: 0x0) but object was missing attribute capsule
```

Correcting it to pass the right type of argument, it works fine

```py
import torch
import metatensor.torch as mts

block = mts.TensorBlock(
    values=torch.tensor([[1, 2], [3, 5]]),
    samples=mts.Labels(["s"], torch.tensor([[0], [2]])),
    components=[],
    properties=mts.Labels.range("p", 2),
)
labels = mts.Labels(["s"], torch.tensor([[0]]))
mts.slice_block(block, "samples", labels)

tensor = mts.TensorMap(mts.Labels.range("key", 1), [block])
mts.slice(tensor, "samples", labels)
```

**Comment by jwa7** [comment]
Apologies, again a typo in the MWE - I have amended my example above.

For consistency I have repeated the first part of your MWE here @Luthaf. The original `TypeError` problem persists:

```py
import torch
import metatensor.torch as mts

block = mts.TensorBlock(
    values=torch.tensor([[1, 2], [3, 5]]),
    samples=mts.Labels(["s"], torch.tensor([[0], [2]])),
    components=[],
    properties=mts.Labels.range("p", 2),
)
labels = mts.Labels(["s"], torch.tensor([[0]]))
mts.slice_block(block, "samples", labels)
```
Raises:
```TypeError: `block` must be a metatensor TensorBlock, not <class 'torch.ScriptObject'>```

Is it possible that it is something to do with the interaction between development versions I am using? I have installed the relevant packages as follows:
```
# ===== Uninstalls, clear caches
pip uninstall -y pytorch rascaline rascaline-torch
pip cache remove "torch*" 
pip cache remove "rascaline*"
pip uninstall -y metatensor metatensor-core metatensor-operations metatensor-torch metatensor-learn
pip cache remove "metatensor*"

# ===== PyTorch, rascaline, rascaline-torch with CPU-only torch
pip install --extra-index-url https://download.pytorch.org/whl/cpu "rascaline-torch @ git+https://github.com/luthaf/rascaline@ddd880286fa570ee38ab1698f8569c02db484eb8#subdirectory=python/rascaline-torch"

# ===== metatensor
pip install --no-build-isolation --no-deps "metatensor-operations @ git+https://github.com/lab-cosmo/metatensor@69c51302854c391f569416ee474ef227c2a70488#subdirectory=python/metatensor-operations"
pip install --no-build-isolation --no-deps "metatensor-learn @ git+https://github.com/lab-cosmo/metatensor@69c51302854c391f569416ee474ef227c2a70488#subdirectory=python/metatensor-learn"
```

**Comment by jwa7** [comment]
Problem solved with the following installation, using the release version of `metatensor-operations` and `metatensor-learn`:

```
# ===== Uninstalls, clear caches
pip uninstall -y pytorch rascaline rascaline-torch
pip cache remove "torch*" 
pip cache remove "rascaline*"
pip uninstall -y metatensor metatensor-core metatensor-operations metatensor-torch metatensor-learn
pip cache remove "metatensor*"

# ===== PyTorch, rascaline, rascaline-torch with CPU-only torch
pip install --extra-index-url https://download.pytorch.org/whl/cpu "rascaline-torch @ git+https://github.com/luthaf/rascaline@ddd880286fa570ee38ab1698f8569c02db484eb8#subdirectory=python/rascaline-torch"

# ===== metatensor
pip install --no-build-isolation --no-deps metatensor-operations metatensor-operations
```

The above issue was caused by an incompatibility between the current main branch versions of `metatensor-operations` and `metatensor-learn` vs the `metatensor-torch` release version installed by `rascaline-torch`. This would be solved by making a new release of these three packages.

Is this a fair summary @Luthaf ?

**Comment by Luthaf** [comment]
Yes! Everything on PyPI should work together, but mixing and matching PyPI releases with developement version comes with some risks.
