### ISSUE TITLE
`to(device)` does not work

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#555]
It would be useful (especially for newcomers) to get the `.to(device)` syntax to work (as opposed to `.to(device=device)`) for `Labels`, `TensorBlock` and `TensorMap`. I don't know how easy this would be though.

EDIT: and also `System`

**Comment by Luthaf** [comment]
This is a bit hard, because we can not differentiate between positional and keyword argument. We could check for both device or dtype on the C++ side, but that would mean that `to(dtype=torch.device("cpu"))` would work.

**Comment by frostedoyster** [comment]
I think torch overloads it as

```
to(device, dtype=None)

to(dtype, device=None)
```

Would that work?

**Comment by Luthaf** [comment]
I'll triple check, but I'm pretty sure we can not do function overloading from TorchScript (torch itself can do more than just TorchScript).

**Comment by Luthaf** [comment]
Yes, trying to define two functions with 

```
.def("to", [](TorchTensorBlock self, torch::Dtype dtype, torch::optional<torch::Device> device) {
    throw "not implemented";
})
.def("to", [](TorchTensorBlock self, torch::Device device, torch::optional<torch::Dtype> dtype) {
    throw "not implemented";
})
```

Gives this error at runtime:

```
 c10::Error: Can't redefine method: to on class: __torch__.torch.classes.metatensor.TensorBlock (of Python compilation unit at: 0x0)
Exception raised from addMethod at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/class_type.cpp:20 (most recent call first):
frame #0: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 92 (0x112322d4c in libc10.dylib)
frame #1: c10::ClassType::addMethod(torch::jit::Function*) + 592 (0x28a1ea6e4 in libtorch_cpu.dylib)
frame #2: TORCH_LIBRARY_init_metatensor(torch::Library&) + 31308 (0x143f82fa4 in libmetatensor_torch.dylib)
```

So we can only have one function, which then does whatever it needs. 

-----

We could cheat by having an extra positional parameter:

```
def to(self, __hidden: Union[Dtype, Device, None], dtype: Optional[Dtype]=None, device: Optional[Device]=None)
```

And then error if `__hidden` is a Dtype and `dtype` is present; or if `__hidden`  is a Device and `device` is present.
