### ISSUE TITLE
Fix the documentation preview 

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/metatensor#576]
Currentlty our jobs on ReadtheDocs are always cancelled at some point. Might be that this is because we run on a too small machine as we had for rascaline.

```
      [ 90%] Building CXX object CMakeFiles/metatensor_torch.dir/src/register.cpp.o
      c++: fatal error: Killed signal terminated program cc1plus
      compilation terminated.
```

We should fix this. As for rascaline I can ask if they can move our jobs on a bigger machine. For rascaline this helped. If for some reason this is not helping we should consider just printing a link to download the docs as we do it in the [cookbook](https://github.com/lab-cosmo/software-cookbook/pull/34)

**Comment by Luthaf** [comment]
Fixed in #611
