### ISSUE TITLE
Let users rename Labels for keys, samples, properties (and perhaps components)

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/metatensor#61]
It would be useful to have some TensorMap and TensorBlock class methods that let the user rename Labels, such as keys, samples, properties, and perhaps components too.

This would allow for greater transferability and interoperability between equistore-based workflows, such as those produced by individuals/groups in different fields and with different naming conventions. 

For example, a user might convert into a typical equistore-native naming convention from data produced by an outside source in the following way:
```py
from equistore import io, Labels, TensorBlock, TensorMap

descriptor = io.load('descriptor.npz', use_numpy=False)

# i.e. for TensorMap keys
descriptor.keys.names
>>> ('spherical_harmonics_l', 'element')

descriptor.rename_keys(['spherical_harmonics_l', 'species_center']
descriptor.keys.names
>>> ('spherical_harmonics_l', 'species_center')

# i.e. for TensorBlock samples
descriptor.block(0).samples.names
>>> ('mol_id', 'atom_id')

descriptor.rename_samples(['structure', 'atom'])
descriptor.block(0).samples.names
>>> ('structure', 'atom')
```

Currently, the only solution (AFAIK) is to manually build new TensorMaps with the desired label names by brute-force iteration over every dimension of every block.

Of course, considerations need to be made wrt (im)mutability and memory allocation - i.e. create a new TensorMap and just reassign the variable like ``descriptor = descriptor.rename_keys()`` (similar to #58) or just reassign Label names Rust-side.

**Comment by Luthaf** [comment]
This is implemented in the `rename_dimension` operation.
