### ISSUE TITLE
`metatensor.learn.Dataset` does not accept field which are not valid Python identifiers

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#621]
In `metatensor.atomsitic`, we're requiring non-standard outputs to be `something::output_name`, but this is not compatible with `metatensor.learn.Dataset`, which works with named tuples.

**Comment by Luthaf** [comment]
We should be able to replace `collection.namedtuple` with our own function than handles fields which are not identifiers.

The output of `collection.namedtuple` can be shown with `verbose=True`, cf https://stackoverflow.com/a/23327320/4692076

I think we would have to skip the `_property(_itemgetter(...` for fields which are not valid identifiers, and maybe add something so the user can do `batch["mtm::something"]` to replace `batch.system` (might be that the `__dict__` already takes care of it).
