### ISSUE TITLE
Error creating `ModelOutput` with `""` quantity

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#624]
```
from metatensor.torch.atomistic import ModelOutput

ModelOutput(
    "hello",
    quantity="",
    unit="",
    per_atom=True,
)
```

results in 

`RuntimeError: !argument.default_value() INTERNAL ASSERT FAILED at "../aten/src/ATen/core/function_schema_inl.h":367, please report a bug to PyTorch. `

**Comment by Luthaf** [comment]
The first argument of `ModelOutput` is already the quantity: https://docs.metatensor.org/latest/atomistic/reference/models/metadata.html#metatensor.torch.atomistic.ModelOutput.

This becomes clear if you remove `quantity=""` from your example, the error becomes 

```
[W model.cpp:1051] Warning: unknown quantity 'hello', only [energy length] are supported (function valid_quantity)
```

I guess this is an issue with how Torch handles `args/kwargs` passing from Python to C++, not sure if we can do much about this.

**Comment by Luthaf** [comment]
I don't think there is much we can do here, this is a fundamental limitation of TorchScript.
