### ISSUE TITLE
Segmentation fault when importing metatensor-torch in Python 3.11

### ISSUE THREAD

**Issue by HannaTuerk** [lab-cosmo/metatensor#663]
Hello,
I installed metatrain with python3.11.0rc1 following the instructions in the documentation (fresh python environment and pip install). I get a 'Segmentation fault (core dumped)' error when I try to run metatrain with mtt in the terminal. With python3.10.12, the same installation procedure works fine.
I had a similar issue with my metatensor-torch installation before on my laptop (the issue above occurred on my workstation), where @Luthaf tracked it down to be related to the reloading of metatensor-torch in  https://github.com/lab-cosmo/metatensor/blob/1356694dc401f53519b176129095f2dc3eb5b58e/python/metatensor-torch/metatensor/torch/operations.py#L59 and replacing 'torch.jit.script' with 'lambda x: x'

I am mostly adding this issue for having it documented in case someone else has a similar problem, for now using python3.10 works for me.

**Comment by Luthaf** [comment]
I'm wondering if there is something wrong in Python `3.11.0rc1`? We might also want to check if this can be reproduced with a more recent release in the 3.11 series.

It is also a bit strange that you have a release candidate installed, did this come from apt?

**Comment by HannaTuerk** [comment]
ok, with python3.11.9 this issue does not exist anymore. So I guess it's really just a problem with python3.11.0rc1, which is the default version you get when you do 'apt install python3.11'. @Luthaf suggested the installation from deadsnakes via ppa (https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) (ppa information: https://geekflare.com/ubuntu-ppa/). This gives you python3.11.9, which works.
Thank you very much for figuring this out, I'll close the issue! :)
