### ISSUE TITLE
`metatensor-torch` from PyPI doesn't work with the torch installation of conda

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#665]
I tried `conda install torch`, then `python -m pip install metatensor[torch]`.
Upon `import metatensor.torch`, I get
```
miniconda3/lib/python3.12/site-packages/metatensor/torch/torch-2.3/lib/libmetatensor_torch.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```
Everything is fine when compiled from source
I got the same error with the CSCS installation of torch, and compiling from source also fixed it in that case

**Comment by Luthaf** [comment]
`conda install torch` does not work with the standard channels or conda-forge (it is named pytorch there). Which channel did you use for this?

**Comment by Luthaf** [comment]
If I use the version for conda-forge, everything works fine for me. Which OS are you running this on? And what's the output of `conda list` (this should give the exact versions and origin of the packages).

I ran `conda install -c conda-forge pytorch` and then `pip install metatensor-torch`.


Below is the relevant output from `conda list`.
```
$ conda list
# packages in environment at /opt/miniforge3:
#
# Name                    Version                   Build  Channel
                                [...]
libtorch                  2.3.1           cpu_generic_hac4f340_0    conda-forge
                                [...]
metatensor-core           0.1.8                    pypi_0    pypi
metatensor-torch          0.5.1                    pypi_0    pypi
                                [...]
pytorch                   2.3.1           cpu_generic_py311h82099cb_0    conda-forge
                                [...]
```

**Comment by frostedoyster** [comment]
I did the same
`conda install -c conda-forge`
`python -m pip install metatensor[torch]`
And I got the same error as before...

**Comment by Luthaf** [comment]
What OS are you running this on? What's the (relevant part of the) output of `conda list`?

**Comment by frostedoyster** [comment]
Ubuntu 24.04
```
metatensor                0.2.0                    pypi_0    pypi
metatensor-core           0.1.8                    pypi_0    pypi
metatensor-learn          0.2.2                    pypi_0    pypi
metatensor-operations     0.2.2                    pypi_0    pypi
metatensor-torch          0.5.1                    pypi_0    pypi

libtorch                  2.3.1           cuda120_h2b0da52_300    conda-forge
metatensor-torch          0.5.1                    pypi_0    pypi
pytorch                   2.3.1           cuda120_py312h26b3cf7_300    conda-forge
```
