### ISSUE TITLE
`slice_block` is slow when operating on very large set of Labels

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/metatensor#700]
In the example below, using this data file  [iron-snapshot.xyz.txt](https://github.com/user-attachments/files/16415631/iron-snapshot.xyz.txt)

Case (A) takes 6.8s, and case (B) takes 360ms!

```py
import rascaline
import metatensor as mts

import numpy as np
import ase.io

frame_iron = ase.io.read("iron-snapshot.xyz", 0)

# selects a subset of the atoms to speed up and remove memory requirements
crop_dz = 16 
crop_idx = np.where(
    (frame_iron.positions[:, 2] < frame_iron.cell[2, 2] / 2 + crop_dz / 2)
    & (frame_iron.positions[:, 2] > frame_iron.cell[2, 2] / 2 - crop_dz / 2)
)[0]
frame_iron = frame_iron[crop_idx]

core_dz = 4
max_cutoff = 6
core_idx = np.sort(
    np.where(
        (frame_iron.positions[:, 0] > max_cutoff + 1)
        & (frame_iron.positions[:, 0] < 199 - max_cutoff)
        & (frame_iron.positions[:, 1] > max_cutoff + 1)
        & (frame_iron.positions[:, 1] < 199 - max_cutoff)
        & (frame_iron.positions[:, 2] < frame_iron.cell[2, 2] / 2 + core_dz / 2)
        & (frame_iron.positions[:, 2] > frame_iron.cell[2, 2] / 2 - core_dz / 2)
    )[0]
)
frame_core = frame_iron[core_idx]

# compute the full NL
nl_code = rascaline.NeighborList(cutoff=max_cutoff, full_neighbor_list=True)
nl_all = nl_code.compute(frame_iron)

# ==================== (A) select with slice_block
# %%time
nl_selected = mts.slice_block(
    nl_all.block(0),
    axis="samples",
    labels=mts.Labels(names=["first_atom"], values=core_idx[:,np.newaxis])
)

# ==================== (B) manual selection
# %%time
labs = core_idx
samp = np.asarray(nl_all.block(0).samples["first_atom"])
mask = np.zeros(len(samp), dtype=bool)

# sorting order and reverse order
sort_idx = np.argsort(samp)
sort_inv = np.argsort(sort_idx)
sort_samp = samp[sort_idx]

# now blocks with the same atom are contiguous so we can use searchsorted to find the bounds
lower = np.searchsorted(sort_samp, labs)
upper = np.searchsorted(sort_samp, labs + 1)


for l, u in zip(lower, upper):
    mask[l:u] = True
mask = mask[sort_inv]

# actually we better extract a classical NL
neigh_dx = nl_all.block(0).values[sort_idx][mask].squeeze()
neigh_sz = upper - lower
neigh_i = np.cumsum(neigh_sz) - neigh_sz[0]
neigh_dr = np.sqrt((neigh_dx**2).sum(axis=1))
```

#692 might help to make the selection faster, but barring that we could also implement a special case in `slice_block` when there is a single dimension in selected labels.

This was found by @ceriottm while working on https://github.com/ceriottm/aml-intro/.

**Comment by PicoCentauri** [comment]
I think this will also apply to `split_block`, where I am currently facing that the operations are also very slow.

**Comment by ceriottm** [comment]
Yes, this is a split_block problem, really. I tried several alternative approaches, and all get super-slow when selecting from a very large list - this is because it has to go through the whole list to check if each of the entries is there. by sorting this is made much faster. I think this also suggests we should resurrect the idea of keeping a flag that says whether a label list is sorted as that would avoid the initial sorting step.

**Comment by Luthaf** [comment]
#692 fixes the speed issue for this issue without requiring a sorted flag (by introducing `Labels.select(selection: Labels) -> List[int]`). However the fix is specific to `slice_block`, which does not call `split_block` internally. @PicoCentauri can you share an example of slow code? I can maybe fix it as well in #692.

**Comment by PicoCentauri** [comment]
Ahh I thpught it does. Yes sure let me try to build example. I faced speed issues when trying to split a metatensor neigborlist.

**Comment by Luthaf** [comment]
My bad here, `split_block` does call `slice_block`, so if the speed issue is the same it will be fixed by the PR.
