### ISSUE TITLE
Advanced indexing of tensor blocks

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/metatensor#97]
Adding index access functionalities which are inspired by numpy
```python
indices = np.where(X == something)[0]
X[indices]
```
The position function already returns one index
```python
index = tensor_block.properties.position((0,1))
```
But something in a similar spirit as the `blocks_matching` function would be nice
```python
indices = tensor_block.properties.position(Labels(names=["n"], values=[[0]]) # returns a tensor block with all properties that fulfill n=0 in the Labels
```
Already talked with @Luthaf about this. Here details from him which might be important for an implementation

> The function is called from here, with a Labels for selection https://github.com/lab-cosmo/equistore/blob/e65cd07d2f0d5aefa41a7b2beade835b9b1dc03b/python/src/equistore/tensor.py#L266-L271
(i.e. to get all n=0, you would give Labels(names=["n"], values=[[0]])
It ends up here after passing through C: https://github.com/lab-cosmo/equistore/blob/e65cd07d2f0d5aefa41a7b2beade835b9b1dc03b/src/tensor/mod.rs#L190, so this is the function we could extract out of the TensorMap and make available for arbitrary Labels (something like Labels::matching(Labels selection).
We are also doing something similar in rascaline, so standardizing everything in equistore would be nice

**Comment by agoscinski** [comment]
I would add to this to this issue. The `position` only returns the index, but often I want to create a tensor block object out of this selection. So another method that returns directly a tensor block for this this subselection. Something like

```python
tensor_block.select_properties(':5') # returns a tensor block with all blocks containing the first 5 properties
tensor_block.select_properties(Labels(names=["n"], values=[[0]])) # returns a tensor block with all blocks containing properties with n=0
```

**Comment by Luthaf** [comment]
> tensor_block.select_properties(':5')

I'm not sure I see the point of this version. There is no special meaning to the first 5 properties, so why would you want to extract them? 

---

From an API point of view, I think these function should work on `Labels`, not `TensorBlock`. We can then use these new functions to make the [`slice`](https://lab-cosmo.github.io/equistore/latest/reference/python/operations/slice.html) operation faster, and use them when we need to slice TensorMap/TensorBlock.

**Comment by agoscinski** [comment]
> I'm not sure I see the point of this version. There is no special meaning to the first 5 properties, so why would you want to extract them?

Right for properties it seems not so useful, but for samples to get very quickly a subset I see applications. I will put this in a separate issue because I think this goes more about the usability of the slices and selections while this issue is more about having the feature at all somewhere availabe.

---
> From an API point of view, I think these function should work on Labels, not TensorBlock. We can then use these new functions to make the [slice](https://lab-cosmo.github.io/equistore/latest/reference/python/operations/slice.html) operation faster, and use them when we need to slice TensorMap/TensorBlock.

Isn't this weird that labels returns a Tensor Block? Does the label have a reference to the block it is assigned to? I guess if one assigns it to the labels, one can make one function and then you don't need multiple function for each dimension of the block.

**Comment by Luthaf** [comment]
> Isn't this weird that labels returns a Tensor Block? Does the label have a reference to the block it is assigned to? I guess if one assigns it to the labels, one can make one function and then you don't need multiple function for each dimension of the block.

What I'm suggesting is to add a single function

```
class Labels:
    # function name up for debate
    def find_matching(self, selection: Labels) -> List[int]:
        ...
```

Then we can build slicing of a single block or a full tensormap based on that (slicing the data itself with the list of integers returned by the `find_matching` function)

**Comment by agoscinski** [comment]
Seems like a good way to go for me
